# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://www.selenium.dev/selenium-ide/")
    self.driver.set_window_size(1054, 808)
    self.driver.find_element(By.LINK_TEXT, "Docs").click()
    self.driver.find_element(By.LINK_TEXT, "API").click()
    self.driver.find_element(By.LINK_TEXT, "Plugins").click()
    self.driver.find_element(By.LINK_TEXT, "Blog").click()
    self.driver.find_element(By.LINK_TEXT, "Help").click()
    self.driver.find_element(By.LINK_TEXT, "Docs").click()
    assert self.driver.title == "Getting Started · Selenium IDE"
    assert self.driver.find_element(By.CSS_SELECTOR, ".navGroup:nth-child(1) > .navGroupCategoryTitle").text == "Introduction"
    self.driver.find_element(By.CSS_SELECTOR, ".postHeaderTitle").click()
    self.driver.find_element(By.CSS_SELECTOR, ".docMainWrapper").click()
    self.driver.find_element(By.CSS_SELECTOR, ".post").click()
    self.driver.find_element(By.CSS_SELECTOR, ".postHeaderTitle").click()
    self.driver.find_element(By.CSS_SELECTOR, ".docMainWrapper").click()
    self.driver.find_element(By.CSS_SELECTOR, "h2:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "h2:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "article").click()
  
